--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

-- Started on 2025-09-17 23:58:10 +07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16414)
-- Name: product_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_categories (
    categories text NOT NULL
);


ALTER TABLE public.product_categories OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16407)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    p_id bigint NOT NULL,
    p_name text NOT NULL,
    p_category text NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16428)
-- Name: products_P_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN p_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."products_P_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3438 (class 0 OID 16414)
-- Dependencies: 216
-- Data for Name: product_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product_categories (categories) VALUES ('bread');
INSERT INTO public.product_categories (categories) VALUES ('cake');
INSERT INTO public.product_categories (categories) VALUES ('cookie');


--
-- TOC entry 3437 (class 0 OID 16407)
-- Dependencies: 215
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.products (p_id, p_name, p_category) VALUES (4, 'Chocolate Cake', 'cake');
INSERT INTO public.products (p_id, p_name, p_category) VALUES (3, 'Cheese Bread', 'bread');
INSERT INTO public.products (p_id, p_name, p_category) VALUES (2, 'White Bread', 'bread');
INSERT INTO public.products (p_id, p_name, p_category) VALUES (1, 'Milk Bread', 'bread');


--
-- TOC entry 3445 (class 0 OID 0)
-- Dependencies: 217
-- Name: products_P_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."products_P_id_seq"', 1, true);


--
-- TOC entry 3290 (class 2606 OID 16413)
-- Name: products Product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "Product_pkey" PRIMARY KEY (p_id);


--
-- TOC entry 3292 (class 2606 OID 16420)
-- Name: product_categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (categories);


--
-- TOC entry 3293 (class 2606 OID 16421)
-- Name: products P_categoryFK; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT "P_categoryFK" FOREIGN KEY (p_category) REFERENCES public.product_categories(categories) NOT VALID;


-- Completed on 2025-09-17 23:58:10 +07

--
-- PostgreSQL database dump complete
--

